### ISSUE TITLE
Advanced topics of Data Science of Python

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/dec-python-course#34]
👋 Hello! It is absolutely great to see this initiative (alongside other courses offered by DIME). For [Development Data Partnership](https://datapartnership.org), we curate examples and tutorials (mostly in Python) for leveraging third-party data opportunities; so an intro to Python is very welcomed. 

Could you please share the roadmap and whether this project would be open to contributions? I'll be more than happy to chip in.

**Comment by luisesanmartin** [comment]
Hi Gabriel. Sure! We'd be happy to have you or the Development Data Partnership contributing to the course. I'm sending you an email with the roadmap we devised and we continue the conversation from there
