### ISSUE TITLE
Session3 Feb2023

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dec-python-course#42]

**Comment by luisesanmartin** [comment]
- [ ] Add how to replace df values based on conditions for Pandas
- [ ] Step 2, exercise 3.2.5: add a suggestion to use `df.tail()`

**Comment by kbjarkefur** [comment]
Should we start introducing numpy in session 2? Guarav had more time there, than Wei had today?

**Comment by weilu** [comment]
Conditional value replacement added to 3.2.3 `singapore_cars.loc[singapore_cars.fuel == 'Petrol', "fuel"] = 'Gasoline'`
3.3.1 example updated with `reset_index(drop=True)` and `sort_values(ignore_index=True)` as an alternative

**Comment by weilu** [comment]
> Should we start introducing numpy in session 2? Guarav had more time there, than Wei had today?

@kbjarkefur as discussed, let's try skipping the numpy section altogether for this upcoming course run and see how it goes.
